Updated to included dialogue and moved yast crowbar and install-suse-cloud out of the automation Added the SUSE Cloud Admin Appliance Guide to help walk you through the installation.

diff --git a/setup-suse-crowbar b/setup-suse-crowbar
--- a/setup-suse-crowbar
+++ b/setup-suse-crowbar
@@ -10,11 +10,145 @@
 #
 
 #variables
-repo_dir="/var/www/htdocs/repo/"
+DIALOG_TITLE=" Prepare SUSE Cloud 3 Admin "
+repo_dir="/srv/www/htdocs/repo/"
+LOGFILE=/var/log/prepare-admin.log
+run_succeeded=
+
+# Infrastructure for nice output/logging
+# --------------------------------------
+
+# Copy stdout to fd 3
+exec 3>&1
+# Create fd 4 for logfile
+exec 4>> "$LOGFILE"
+
+if [ -z "$CROWBAR_VERBOSE" ]; then
+    # Set fd 1 and 2 to logfile
+    exec 1>&4 2>&1
+else
+    # Set fd 1 and 2 to logfile (and keep stdout too)
+    exec 1> >( tee -a /dev/fd/4 ) 2>&1
+fi
+# Send summary fd to original stdout
+exec 6>&3
+
+use_dialog () {
+    [ -z "$CROWBAR_VERBOSE" -a -t 3 -a -x "$(type -p dialog)" ]
+}
+
+pipe_show_and_log () {
+    if use_dialog; then
+        t=$(mktemp)
+        cat - > $t
+        dialog --title "$DIALOG_TITLE" --textbox -- $t $(($(wc -l <$t)+4)) 75 >&3
+        rm -f $t
+        dialog --clear >&3
+    fi
+    tee -a /dev/fd/3 /dev/fd/4 > /dev/null
+}
+
+# Draw a spinner so the user knows something is happening
+spinner () {
+    local delay=0.75
+    local spinstr='/-\|'
+    local msg="$@"
+
+    # reset exit handler
+    trap "exit" EXIT
+
+    printf "... " >&3
+    while [ true ]; do
+        local temp=${spinstr#?}
+        if use_dialog; then
+            printf "\n%s [%c]" "$msg... " "$spinstr" | dialog --title "$DIALOG_TITLE" \
+                --keep-window --progressbox 5 70 >&3
+        else
+            printf "[%c]" "$spinstr" >&3
+        fi
+        local spinstr=$temp${spinstr%"$temp"}
+        sleep $delay
+        if ! use_dialog; then
+            printf "\b\b\b" >&3
+        fi
+    done
+}
+
+kill_spinner () {
+    if [ ! -z "$LAST_SPINNER_PID" ]; then
+        kill >/dev/null 2>&1 $LAST_SPINNER_PID
+        if [ $# -eq 0 ]; then
+            printf "\b\b\bdone\n" >&3
+        else
+            printf "\b\b\b$*\n" >&3
+        fi
+        unset LAST_SPINNER_PID
+    fi
+}
+
+kill_spinner_with_failed () {
+    kill_spinner "failed"
+}
+
+echo_log () {
+    echo -e === "$(date '+%F %T %z'): $@" >&4
+}
+
+echo_summary () {
+    # Also send summary to logfile
+    echo_log $@
+
+    kill_spinner
+
+    if [ -z "$CROWBAR_VERBOSE" ]; then
+        if [ -t 3 ]; then
+            echo -n -e $@ >&3
+            if use_dialog; then
+                echo -n -e $@ | dialog --title "$DIALOG_TITLE" --progressbox 8 60 >&3
+            fi
+            # Use disown to lose job control messages (especially the
+            # "Completed" message when spinner will be killed)
+            ( spinner $@ ) & disown
+            LAST_SPINNER_PID=$!
+        else
+            echo -e $@ >&3
+        fi
+    else
+        echo -e === $@ >&3
+    fi
+}
+
+echo_summary_no_spinner () {
+    # Also send summary to logfile
+    echo_log $@
+
+    kill_spinner
+
+    if [ -z "$CROWBAR_VERBOSE" ]; then
+        echo -e $@ >&3
+    else
+        echo -e === $@ >&3
+    fi
+}
 
 die() {
-  echo >&2 "$*"
-  exit 1
+    # Send empty line & error to logfile
+    echo >&4
+    echo_log "Error: $@"
+
+    kill_spinner_with_failed
+
+    if use_dialog; then
+        dialog --title "$DIALOG_TITLE" --clear --msgbox -- "Error: $@" 8 73 >&3
+        # avoid triggering two dialogs in a row
+        run_succeeded=already_died
+    else
+        echo >&3
+        echo -e "Error: $@" >&3
+    fi
+
+    res=1
+    exit 1
 }
 
 setup_cloud_network() {
@@ -25,6 +159,7 @@ setup_local_smt() {
   
   if [ -d "$repo_dir" ]; then
   tar -xJvf /srv/tftpboot/txz/SUSE-Cloud-3-repos-03182014.txz -C $repo_dir 
+  chown -R smt:www /srv/www/htdocs/repo/\$RCE/
   else 
   echo "$repo_dir does not exist"
   fi 
@@ -48,10 +183,7 @@ mirror_smt_repos() {
     smt repos -e $REPO sle-11-x86_64
   done
   
-  echo -e '\n'
-  echo 'The system will now mirror the proper repositories for SUSE Cloud.\n
-        This process will take over an hour depending on your bandwidth.'
-  echo -e '\n'
+  echo -e 'The system will now mirror any remaining packages from the included repos\n'
   
   smt-mirror
   [[ $? -ne 0 ]] && die "Failed to Mirror repos"
@@ -72,19 +204,51 @@ install_suse_cloud() {
 
 main() {
 
+  echo_summary "Setup SMT repos"
   setup_local_smt
       
+  echo_summary "Checking SMT repos for updated packages"
   mirror_smt_repos
+  echo_summary "Linking SMT repos properly"
   link_smt_repos
-    
-  setup_cloud_network
-   
-  remove_ncc_repos 
-
-  install_suse_cloud
   
+  #removing to setup after all preparations are complete  
+  #setup_cloud_network
+  
+  echo_summary "Disabling remote repos" 
+  remove_ncc_repos 
+#FIXME - removing as it fails because proper env is not set  
+  #install_suse_cloud
+  
+  echo_summary "Clean up"
   insserv setup-crowbar -r
   mv /etc/init.d/suse_studio_firstboot /tmp/
+  
+  echo_summary "Preparation Complete!"
+  kill_spinner
+  cat <<EOF | pipe_show_and_log
+
+ The Admin node has been prepared. To finish the installation
+ you will need to define the network configuration that
+ you defined while going through the questionnaire along with 
+ the deployment guide. 
+
+ At the login prompt you may login as root and execute
+
+        yast crowbar 
+
+ Once your network settings are all defined then continue the 
+ install and execute         
+
+	screen install-suse-cloud 
+
+ Before you proceed with install-suse-cloud its important that
+ the network settings are properly defined and that you have 
+ everything right otherwise you will need to start over. 
+EOF
+
+run_succeeded=hooray
+exit 0
 }
 
 main "$@"
