shell code needs consistent indentation. Closes #11

diff --git a/kiwi/root/studio/overlay-tmp/files/etc/init.d/suse_studio_firstboot b/kiwi/root/studio/overlay-tmp/files/etc/init.d/suse_studio_firstboot
--- a/kiwi/root/studio/overlay-tmp/files/etc/init.d/suse_studio_firstboot
+++ b/kiwi/root/studio/overlay-tmp/files/etc/init.d/suse_studio_firstboot
@@ -7,53 +7,51 @@ ISODIR="/srv/tftpboot/iso"
 REPOSDIR="/srv/tftpboot/repos"
 
 die() {
-  echo >&2 "$*"
-  exit 1
+    echo >&2 "$*"
+    exit 1
 }
 
 setup_local_sles_repos() {
-mkdir -p /srv/tftpboot/suse-11.3/install/
-# mount SLES 11 SP3 ISO
-mount -o loop $ISODIR/SLES-11-SP3-DVD-x86_64-GM-DVD1.iso /srv/tftpboot/suse-11.3/install
-
-zypper --gpg-auto-import-keys refresh
-zypper ar --refresh file:///srv/tftpboot/suse-11.3/install/ "SLES 11 SP3 Media"
+    mkdir -p /srv/tftpboot/suse-11.3/install/
+    # mount SLES 11 SP3 ISO
+    mount -o loop $ISODIR/SLES-11-SP3-DVD-x86_64-GM-DVD1.iso /srv/tftpboot/suse-11.3/install
+    # Add repos to zypper
+    zypper --gpg-auto-import-keys refresh
+    zypper ar --refresh file:///srv/tftpboot/suse-11.3/install/ "SLES 11 SP3 Media"
 }
 
 setup_local_cloud_repos() {
-mkdir -p $REPOSDIR/Cloud/
-# mount SUSE Cloud 3 ISO
-mount -o loop $ISODIR/SUSE-CLOUD-3-x86_64-GM-DVD1.iso $REPOSDIR/Cloud
-
-zypper --gpg-auto-import-keys refresh
-zypper ar --refresh file://$REPOSDIR/Cloud/ "SUSE-Cloud-3"
+    mkdir -p $REPOSDIR/Cloud/
+    # mount SUSE Cloud 3 ISO
+    mount -o loop $ISODIR/SUSE-CLOUD-3-x86_64-GM-DVD1.iso $REPOSDIR/Cloud
+    # Add repos to zypper
+    zypper --gpg-auto-import-keys refresh
+    zypper ar --refresh file://$REPOSDIR/Cloud/ "SUSE-Cloud-3"
 }
 
 setup_fstab_iso_mounts() {
-echo "$ISODIR/SLES-11-SP3-DVD-x86_64-GM-DVD1.iso    /srv/tftpboot/suse-11.3/install   iso9660   loop,auto   0 0" >> /etc/fstab
-echo "$ISODIR/SUSE-CLOUD-3-x86_64-GM-DVD1.iso    $REPOSDIR/Cloud   iso9660   loop,auto   0 0" >> /etc/fstab
+    echo "$ISODIR/SLES-11-SP3-DVD-x86_64-GM-DVD1.iso    /srv/tftpboot/suse-11.3/install   iso9660   loop,auto   0 0" >> /etc/fstab
+    echo "$ISODIR/SUSE-CLOUD-3-x86_64-GM-DVD1.iso    $REPOSDIR/Cloud   iso9660   loop,auto   0 0" >> /etc/fstab
 }
 
 setup_local_smt_repo() {
-zypper ar -c -t yast2 iso:/?iso=$ISODIR/SLE-11-SP3-SMT-GM-Media1.iso "SMT for SLES11SP3"
-zypper --gpg-auto-import-keys refresh
-zypper in -y --auto-agree-with-licenses -t pattern SMT lamp_server   
+    zypper ar -c -t yast2 iso:/?iso=$ISODIR/SLE-11-SP3-SMT-GM-Media1.iso "SMT for SLES11SP3"
+    zypper --gpg-auto-import-keys refresh
+    zypper in -y --auto-agree-with-licenses -t pattern SMT lamp_server   
 }
 
 install_cloud_admin() {
-zypper --gpg-auto-import-keys refresh
-zypper in -y --auto-agree-with-licenses --force-resolution -t pattern cloud_admin
-[[ $? -ne 0 ]] && die "Failed to install cloud_admin pattern"
+    zypper --gpg-auto-import-keys refresh
+    zypper in -y --auto-agree-with-licenses --force-resolution -t pattern cloud_admin
+    [[ $? -ne 0 ]] && die "Failed to install cloud_admin pattern"
 }
 
 main() {
-  
-  setup_local_sles_repos
-  setup_local_cloud_repos
-  setup_fstab_iso_mounts
-  setup_local_smt_repo
-  
-  install_cloud_admin    
+    setup_local_sles_repos
+    setup_local_cloud_repos
+    setup_fstab_iso_mounts
+    setup_local_smt_repo
+    install_cloud_admin    
 }
 
 main "$@"
diff --git a/kiwi/root/studio/overlay-tmp/files/usr/bin/setup-suse-crowbar b/kiwi/root/studio/overlay-tmp/files/usr/bin/setup-suse-crowbar
--- a/kiwi/root/studio/overlay-tmp/files/usr/bin/setup-suse-crowbar
+++ b/kiwi/root/studio/overlay-tmp/files/usr/bin/setup-suse-crowbar
@@ -154,71 +154,66 @@ die() {
 }
 
 setup_local_smt() {
-  if [ -d "$txz_dir" ]; then
-  mkdir -p /srv/www/htdocs/repo/\$RCE/  
-    if cat /srv/tftpboot/txz/SUSE-Cloud-3-repos-03182014.txz.part0* | tar -xJv -C $repo_dir; then
-       rm /srv/tftpboot/txz/SUSE-Cloud-3-repos-03182014.txz.part0*
+    if [ -d "$txz_dir" ]; then
+        mkdir -p /srv/www/htdocs/repo/\$RCE/  
+        if cat /srv/tftpboot/txz/SUSE-Cloud-3-repos-03182014.txz.part0* | tar -xJv -C $repo_dir; then
+            rm /srv/tftpboot/txz/SUSE-Cloud-3-repos-03182014.txz.part0*
     fi
-  chown -R smt:www /srv/www/htdocs/repo/\$RCE/
-  else 
-  echo "$txz_dir does not exist. Must be Standard Image"
-  fi 
-  smt-ncc-sync
-  
+    chown -R smt:www /srv/www/htdocs/repo/\$RCE/
+    else 
+        echo "$txz_dir does not exist. Must be Standard Image"
+    fi 
+    smt-ncc-sync
 }
 
 link_smt_repos() {
-  for REPO in SLES11-SP3-{Pool,Updates} SUSE-Cloud-3.0-{Pool,Updates} SLE11-SMT-SP3-{Pool,Updates} SLE11-HAE-SP3-{Pool,Updates}; do
-    ln -s $repo_dir\$RCE/$REPO/sle-11-x86_64 /srv/tftpboot/repos/${REPO/.0/}
-  done
+    for REPO in SLES11-SP3-{Pool,Updates} SUSE-Cloud-3.0-{Pool,Updates} SLE11-SMT-SP3-{Pool,Updates} SLE11-HAE-SP3-{Pool,Updates}; do
+        ln -s $repo_dir\$RCE/$REPO/sle-11-x86_64 /srv/tftpboot/repos/${REPO/.0/}
+    done
 }
 
 mirror_smt_repos() {
-  #smt repos -e SUSE-Cloud-3.0-Pool 
-  #smt repos -e SUSE-Cloud-3.0-Updates 
-  #smt repos -e SLES11-SP3-Pool sle-11-x86_64
-  #smt repos -e SLES11-SP3-Updates sle-11-x86_64
+    #smt repos -e SUSE-Cloud-3.0-Pool 
+    #smt repos -e SUSE-Cloud-3.0-Updates 
+    #smt repos -e SLES11-SP3-Pool sle-11-x86_64
+    #smt repos -e SLES11-SP3-Updates sle-11-x86_64
   
-  for REPO in SLES11-SP3-{Pool,Updates} SUSE-Cloud-3.0-{Pool,Updates} SLE11-SMT-SP3-{Pool,Updates} SLE11-HAE-SP3-{Pool,Updates}; do
-    smt repos -e $REPO sle-11-x86_64
-  done
+    for REPO in SLES11-SP3-{Pool,Updates} SUSE-Cloud-3.0-{Pool,Updates} SLE11-SMT-SP3-{Pool,Updates} SLE11-HAE-SP3-{Pool,Updates}; do
+        smt repos -e $REPO sle-11-x86_64
+    done
   
-  echo -e 'The system will now mirror any remaining packages from the included repos\n'
+    echo -e 'The system will now mirror any remaining packages from the included repos\n'
   
-  smt-mirror
-  [[ $? -ne 0 ]] && die "Failed to Mirror repos"
+    smt-mirror
+    [[ $? -ne 0 ]] && die "Failed to Mirror repos"
 }
 
 remove_ncc_repos() {
-  for REPO in SLES11-SP3-{Pool,Updates} SUSE-Cloud-3.0-{Pool,Updates} SLE11-SMT-SP3-{Pool,Updates}; do
-      zypper mr -d $REPO
-  done
+    for REPO in SLES11-SP3-{Pool,Updates} SUSE-Cloud-3.0-{Pool,Updates} SLE11-SMT-SP3-{Pool,Updates}; do
+        zypper mr -d $REPO
+    done
 }
 
 main() {
-
-  echo_summary "Setup SMT repos"
-  setup_local_smt
-  if [ -d "$txz_dir" ]; then
-  echo_summary "Checking SMT repos for updated packages" 
-  else    
-  echo_summary "Mirroring SMT repos... This will take awhile"
-  fi
-  mirror_smt_repos
-  echo_summary "Linking SMT repos properly"
-  link_smt_repos
-      
-  echo_summary "Disabling remote repos" 
-  remove_ncc_repos 
-  
-  echo_summary "Clean up"
-  insserv setup-crowbar -r
-  mv /etc/init.d/suse_studio_firstboot /tmp/
-  
-  echo_summary "Preparation Complete!"
-  kill_spinner
-  
-  exit 0
+    echo_summary "Setup SMT repos"
+    setup_local_smt
+    if [ -d "$txz_dir" ]; then
+        echo_summary "Checking SMT repos for updated packages" 
+    else    
+        echo_summary "Mirroring SMT repos... This will take awhile"
+    fi
+    mirror_smt_repos
+    echo_summary "Linking SMT repos properly"
+    link_smt_repos
+    echo_summary "Disabling remote repos" 
+    remove_ncc_repos 
+    echo_summary "Clean up"
+    # Cleanup firstboot
+    insserv setup-crowbar -r
+    mv /etc/init.d/suse_studio_firstboot /tmp/
+    echo_summary "Preparation Complete!"
+    kill_spinner
+    exit 0
 }
 
 main "$@"
